name: Draft Release with Notes and Build Artifacts
on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:
        inputs:
            tag_name:
                description: "Tag to create/release (e.g. v1.2.3-test.1)"
                required: true
                type: string


jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ inputs.tag_name || github.ref_name }}
                target_commitish: ${{ github.sha }}
                draft: true
                generate_release_notes: true
                append_body: true
                files: dist/*.js
